#ifndef RECEIVED_MESSAGE_TYPE_H
#define RECEIVED_MESSAGE_TYPE_H
#include <Arduino.h>

enum ReceivedMessageType: byte
{
    CONNECT=0,CHECK_SCORE=1,UP_PRESSED=2,UP_FREE=3,DISCONNECT=4
};

#endif//RECEIVED_MESSAGE_TYPE_H